pipeline {
    agent any

    stages {
        stage('Code change') {
            steps {
                git branch: 'main', url: 'https://github.com/up1/workshop-devops-20240515.git'
            }
        }
        stage('Download deps/libs') {
            steps {
                sh '''cd api-nodejs
                      npm ci'''
            }
        }
        stage('Dependency check') {
            steps {
                sh '''cd api-nodejs
                      npm audit fix'''
            }
        }
        stage('Scan code sonarqube') {
            steps {
                build wait: false, job: 'somkiat_sonar'
            }
        }
        stage('Deploy') {
            steps {
                build 'somkiat_deploy'
            }
        }
        stage('API test') {
            steps {
                sh '''cd api-nodejs/postman
                newman run hello-nodejs.postman_collection.json
                '''
            }
        }
        stage('Deploy to QA server') {
            steps {
                echo 'Hello World'
            }
        }
    }
}
