services:
  api:
    image: demo-api:1.0
    build:
      context: ./api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_NAME=hellodb
      - DB_USER=user01
      - DB_PASSWORD=${DB_PASSWORD:-password01}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  db:
    image: demo-mysql:1.0
    build:
      context: ./mysql
    environment:
      - MYSQL_DATABASE=hellodb
      - MYSQL_USER=user01
      - MYSQL_PASSWORD=${DB_PASSWORD:-password01}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uuser01", "-ppassword01"]
      interval: 5s
      timeout: 5s
      retries: 10